#!/bin/bash
# Justice Oracle - Production Deployment Script

set -e

echo "🚀 Justice Oracle - Automated Deployment"
echo "========================================"
echo ""

# Check if GenLayer CLI is installed
if ! command -v genlayer &> /dev/null; then
    echo "📦 Installing GenLayer CLI..."
    pip install genlayer-cli
fi

# Check if contract file exists
if [ ! -f "contracts/JusticeOracle.py" ]; then
    echo "❌ Error: contracts/JusticeOracle.py not found"
    exit 1
fi

echo "✅ Contract found"
echo ""

# Deploy to GenLayer testnet
echo "📤 Deploying contract to GenLayer testnet..."
echo "   (This uses your local GenLayer node or testnet RPC)"
echo ""

# Deploy using GenLayer CLI
CONTRACT_ADDRESS=$(genlayer deploy contracts/JusticeOracle.py --network testnet --output address)

if [ -z "$CONTRACT_ADDRESS" ]; then
    echo "❌ Deployment failed"
    exit 1
fi

echo "✅ Contract deployed successfully!"
echo "📍 Address: $CONTRACT_ADDRESS"
echo ""

# Update frontend .env.local
echo "⚙️  Configuring frontend..."
cd frontend

cat > .env.local << EOF
# Auto-generated by deploy.sh
# GenLayer testnet configuration

NEXT_PUBLIC_GENLAYER_RPC=https://studio.genlayer.com/api
NEXT_PUBLIC_CONTRACT_ADDRESS=$CONTRACT_ADDRESS
NEXT_PUBLIC_NETWORK=testnet
EOF

echo "✅ Frontend configured"
echo ""

# Install frontend dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "📦 Installing frontend dependencies..."
    npm install
fi

echo ""
echo "🎉 Deployment Complete!"
echo "========================================"
echo ""
echo "Contract Address: $CONTRACT_ADDRESS"
echo ""
echo "Next steps:"
echo "  1. cd frontend"
echo "  2. npm run dev"
echo "  3. Open http://localhost:3000"
echo ""
echo "💰 Platform Fees:"
echo "  • File dispute: 10 tokens (minimum stake)"
echo "  • Submit evidence: ~1 token (gas)"
echo "  • Platform fee: 1% of stake"
echo ""
echo "✅ Contract deployed and ready!"
