#!/usr/bin/env python3
"""
Justice Oracle - Local Terminal Deployment
Deploy directly from your terminal without Studio UI
"""

import json
import requests
import os
from pathlib import Path

# Configuration
GENLAYER_RPC = "https://studio.genlayer.com/api"
NETWORK = "testnet"

print("🚀 Justice Oracle - Terminal Deployment")
print("=" * 60)
print()

# Read contract
contract_path = Path("contracts/JusticeOracle.py")
if not contract_path.exists():
    print("❌ Error: contracts/JusticeOracle.py not found")
    exit(1)

with open(contract_path) as f:
    contract_code = f.read()

print("✅ Contract loaded")
print(f"   Lines: {len(contract_code.splitlines())}")
print(f"   Size: {len(contract_code)} bytes")
print()

# Deploy contract
print("📤 Deploying to GenLayer testnet...")
print("   (This may take 30-60 seconds)")
print()

try:
    # Prepare deployment payload
    payload = {
        "jsonrpc": "2.0",
        "method": "deploy_contract",
        "params": {
            "code": contract_code,
            "network": NETWORK,
        },
        "id": 1
    }
    
    # Send deployment request
    response = requests.post(GENLAYER_RPC, json=payload, timeout=120)
    result = response.json()
    
    if "error" in result:
        print(f"❌ Deployment failed: {result['error']['message']}")
        exit(1)
    
    contract_address = result["result"]["address"]
    
    print("✅ Contract deployed successfully!")
    print(f"📍 Address: {contract_address}")
    print()
    
    # Update frontend .env.local
    print("⚙️  Configuring frontend...")
    
    frontend_dir = Path("frontend")
    env_file = frontend_dir / ".env.local"
    
    env_content = f"""# Auto-generated by deploy_local.py
# GenLayer testnet configuration

NEXT_PUBLIC_GENLAYER_RPC={GENLAYER_RPC}
NEXT_PUBLIC_CONTRACT_ADDRESS={contract_address}
NEXT_PUBLIC_NETWORK={NETWORK}
"""
    
    with open(env_file, "w") as f:
        f.write(env_content)
    
    print("✅ Frontend configured")
    print(f"   Config: {env_file}")
    print()
    
    # Save deployment info
    deployment_info = {
        "contract_address": contract_address,
        "network": NETWORK,
        "rpc": GENLAYER_RPC,
        "min_stake": 10,
        "platform_fee": 1
    }
    
    with open("deployment_info.json", "w") as f:
        json.dump(deployment_info, f, indent=2)
    
    print("✅ Deployment info saved: deployment_info.json")
    print()
    
    # Print summary
    print("🎉 Deployment Complete!")
    print("=" * 60)
    print()
    print(f"📍 Contract: {contract_address}")
    print(f"🌐 Network:  {NETWORK}")
    print(f"🔗 RPC:      {GENLAYER_RPC}")
    print()
    print("💰 Super Affordable Pricing:")
    print("   • File dispute:     10 tokens (stake)")
    print("   • Submit evidence:  ~1 token (gas)")
    print("   • Platform fee:     1% of stake")
    print()
    print("📝 Next steps:")
    print("   1. cd frontend")
    print("   2. npm run dev")
    print("   3. Open http://localhost:3000")
    print()
    print("🎬 Ready to demo!")
    print()

except requests.exceptions.Timeout:
    print("❌ Deployment timed out. Please try again or use GenLayer Studio.")
    print("   URL: https://studio.genlayer.com/")
    exit(1)

except Exception as e:
    print(f"❌ Error: {e}")
    print()
    print("💡 Alternative: Use GenLayer Studio")
    print("   1. Go to https://studio.genlayer.com/")
    print("   2. Upload contracts/JusticeOracle.py")
    print("   3. Click Deploy")
    print("   4. Copy address and run: python3 configure_frontend.py <address>")
    exit(1)
